### ISSUE TITLE
Bugs!

### ISSUE THREAD

**Issue by NelkGames** [Domaman202/LogisticsBridge#11]
hello, i'm playing version 1.4.4 and i noticed some bugs:
1st: Result Logistic Pipe does not save the id after you click the save button.
2nd: the Crafting Manager Pipe has a buggy HUD, the items in the player's inventory are invisible and the buttons that configure the pipe are missing.
![Screenshot_1](https://user-images.githubusercontent.com/19228548/123681766-95e07380-d820-11eb-8544-c5cd2f0b0578.jpg)

**Comment by Domaman202** [comment]
ok, thx!)

**Comment by Domaman202** [comment]
@KorewaLidesu heeeeeeeeeelp please :3

**Comment by KorewaLidesu** [comment]
Sorry, no experience at code.

**Comment by KorewaLidesu** [comment]
@NelkGames Can you right click and open config menu?

**Comment by Domaman202** [comment]
> Sorry, no experience at code.
ok, thx ;3

**Comment by KorewaLidesu** [comment]
Issue can be reproduce in LB 1.4.3 (release) and LP 0.10.3.114

**Comment by KorewaLidesu** [comment]
Is there any change in release 1.4.0 and 1.3.14?

**Comment by NelkGames** [comment]
> @NelkGames Can you right click the module to open config menu?
> 
> P/s: Please include LB & LP version build

I used all ways to access the pipe. In all cases the Hud did not appear.

the version I'm using is:
Logistics Bridge: 1.4.4
Logistics Pipes: 0.10.4.5

**Comment by KorewaLidesu** [comment]
What happen to this? [GuiResultPipe.java](https://github.com/Domaman202/LogisticsBridge/blob/564da6873f469db0267939a4467870e632df74d8/src/main/java/com/tom/logisticsbridge/gui/GuiResultPipe.java#L64) @Domaman202

**Comment by KorewaLidesu** [comment]
@NelkGames download this [artifact](https://github.com/Domaman202/LogisticsBridge/suites/3152199627/artifacts/72478319) and check if it works

**Comment by NelkGames** [comment]
> @NelkGames download this [artifact](https://github.com/Domaman202/LogisticsBridge/suites/3152366907/artifacts/72482644) and check if it works

yes it is working! Thank you very much! :D
![Screenshot_1](https://user-images.githubusercontent.com/19228548/124373796-d2bac900-dc6b-11eb-99c7-17fd9bedbd9a.jpg)

**Comment by KorewaLidesu** [comment]
Please close this issue.
