### ISSUE TITLE
Fluid Crafting settings not being saved

### ISSUE THREAD

**Issue by Timeslice42** [Domaman202/LogisticsBridge#17]
In the crafting manager the fluid setting for the fluid module addons on crafting modules isn't serializing/saving correctly. The *amount* gets saved, but the actual fluid to use gets cleared.

FYI I'll be reverting to the old Logistics Bridge until this is fixed, because RIP all my gregtech fluid crafting...

Logistics Pipes: 0.10.3.114
Logistics Bridge: Unversioned (The one after 1.4.4)

**Comment by Timeslice42** [comment]
Or I guess I won't be reverting since the original author's Logistics Bridge crashes with the latest LP.  Time to play a different modpack :(

**Comment by KorewaLidesu** [comment]
Did you test new version?

**Comment by Timeslice42** [comment]
I'm loading it up now, hopefully I'll have an answer soon.

**Comment by Timeslice42** [comment]
[logs.zip](https://github.com/Domaman202/LogisticsBridge/files/6862518/logs.zip)
 Still no joy. I loaded a world, looked at a Crafting Card in the Crafting Manager that had a Fluid Crafting upgrade. The amount and satellite were listed, but the fluid was blank. I changed the fluid back to what it was supposed to be (Nacre, in this case), quit to menu, and loaded the world again. The fluid was blank again. I can confirm that it is actually blank, as the recipe does not attempt to add fluid when crafting (as opposed to just looking blank).

**Comment by KorewaLidesu** [comment]
Hmmm, I think I may figure out what happen here.

**Comment by KorewaLidesu** [comment]
It is LP bug, please report at [here](https://github.com/RS485/LogisticsPipes/issues) instead

**Comment by Timeslice42** [comment]
Thank you! It's also great to know which version of LP this is targetting, since LP does a lot of alpha, beta, and normal releases.

**Comment by Timeslice42** [comment]
Also, I can confirm that this is working with the latest LP, something I forgot to mention :)
