### ISSUE TITLE
Crafting Manager crashes on blocking mode when attempting to craft

### ISSUE THREAD

**Issue by Timeslice42** [Domaman202/LogisticsBridge#20]
LP: 0.10.4.5
LB: Unversioned (the latest one, after 1.4.4)

I have a recipe that works with a crafting pipe or chassis, but crashes with the crafting manager. My only guess as to why is due to the odd nature of the recipe.
I have a crafting card set with a recipe that has more than 64 items in one slot (two slots with 127 each, plus 7 other itemstacks worth of ingredients). The crafting manager is set to "Wait for empty inventory", and crashes once it has all of the ingredients and it tries to move them to the satellite.

[latest.log](https://github.com/Domaman202/LogisticsBridge/files/6972645/latest.log)

Hopefully you're able to access that log file okay.

**Comment by Domaman202** [comment]
ok thx

**Comment by Domaman202** [comment]
check 1.4.5.1 version

**Comment by Timeslice42** [comment]
Okay, it doesn't crash anymore, but now it just sends the items back to the default route, instead of into the CM's default satellite. Except for anything that was designated for a different satellite. Those go where they are meant to.

**Comment by KorewaLidesu** [comment]
Is there any error when that happen?
Please upload latest.log and debug.log up here

**Comment by Timeslice42** [comment]
There are no errors. Also, I can confirm that it *almost* works as expected if I manually set all of the other ingredients to use the default satellite.

However, now it starts sending the ingredients in early, and never sends the rest in. Basically, it's skipping the extra 63 items from each stack of 127.

**Comment by KorewaLidesu** [comment]
"Wait for empty inventory"

**Comment by Domaman202** [comment]
а без е#учего мода на логи всё работает?

**Comment by Timeslice42** [comment]
Are you asking me a question?

**Comment by Domaman202** [comment]
+

**Comment by Domaman202** [comment]
(Please translate in Google ибо мне самому лень)
крч по логам видно что он крашился из-за очков которые показывают нагрузку на сервер, я не помню как этот мод называется, но попробуйте удалить его и проверить результат.

**Comment by KorewaLidesu** [comment]
@Timeslice42 this thing is complicated tho...

1. `sends the items back to the default route` happen with new version (I don't know who to blame since both LP and LB update).
2. `However, now it starts sending the ingredients in early, and never sends the rest in. Basically, it's skipping the extra 63 items from each stack of 127.` this happen from the past version already (1.3.14).

**Comment by Timeslice42** [comment]
That's called LagGoggles, and that had nothing to do with the crash, which is no longer happening anyways. Lag Goggles just ends up injecting itself into some of the stack traces.

**Comment by Timeslice42** [comment]
> @Timeslice42 this thing is complicated tho...
> 
> 1. `sends the items back to the default route` happen with new version (I don't know who to blame since both LP and LB update).
> 2. `However, now it starts sending the ingredients in early, and never sends the rest in. Basically, it's skipping the extra 63 items from each stack of 127.` this happen from the past version already (1.3.14).

Number 1 was only happening because I was using an Advanced Satellite Upgrade on that crafting recipe, and apparently the Crafting Manager doesn't automatically use the default satellite when you use that upgrade and have ingredients set to no satellite.

**Comment by KorewaLidesu** [comment]
@Domaman202 Need rework on buffer upgrade

**Comment by KorewaLidesu** [comment]
I can't reproduce the `However, now it starts sending the ingredients in early, and never sends the rest in. Basically, it's skipping the extra 63 items from each stack of 127.` issue

**Comment by Timeslice42** [comment]
> I can't reproduce the `However, now it starts sending the ingredients in early, and never sends the rest in. Basically, it's skipping the extra 63 items from each stack of 127.` issue on new version (LP 0.10.4.5 - LB 1.4.5.1)

https://i.imgur.com/3CbOLWV.png

**Comment by KorewaLidesu** [comment]
wait, how did u set that to 127?

**Comment by Timeslice42** [comment]
> wait, how did u set that to 127?

LP has always had a max stack size of 127.

**Comment by KorewaLidesu** [comment]
> > wait, how did u set that to 127?
> 
> LP has always had a max stack size of 127. You can use the mouse wheel, or shift-right click to double.

You can't do that with LB buffer due to exist limitation (64)

**Comment by Timeslice42** [comment]
> > > wait, how did u set that to 127?
> > 
> > 
> > LP has always had a max stack size of 127. You can use the mouse wheel, or shift-right click to double.
> 
> You can't do that with LB buffer due to exist limitation (64)

That would be a bug in LB then. LP has had this functionality for literally six years, at least.

**Comment by KorewaLidesu** [comment]
The issue is LB limitation.
The things is, LB buffer get items out of the chest as buffer *by slot*, meaning that... it won't able to handle that 127 items in 1 slot.

**Comment by Timeslice42** [comment]
Like you said, the buffer upgrade will need a rework.

**Comment by KorewaLidesu** [comment]
> Like you said, the buffer upgrade will need a rework.

It will take alot of time tho, since buffer working as slot, not item inside the buffer chest

**Comment by Timeslice42** [comment]
🤷

**Comment by Timeslice42** [comment]
If you know of another way to get it to send 256 fine copper wires along with the other ingredients while still buffering, I'm all ears.

**Comment by KorewaLidesu** [comment]
Put wiremill next to input 🤷

**Comment by Timeslice42** [comment]
That could work. And is probably better than the janky idea I was cooking up.

**Comment by KorewaLidesu** [comment]
https://github.com/KorewaLidesu/LogisticsBridge/suites/3494884207/artifacts/83233988
Can you try this artifact? *please backup your world first*

**Comment by Timeslice42** [comment]
> Can you try this [artifact](https://github.com/KorewaLidesu/LogisticsBridge/suites/3494884207/artifacts/83233988)? _in test world_
> 
> hope this will resolve issue `the Crafting Manager doesn't send them to the default satellite`

I will try this within the next hour or so. In the mean time I'm going to close this ticket, as the crash has been solved, and open two more for the other issues.
