### ISSUE TITLE
Crafting Manager not using Default Satellite with Advanced Satellite Module Upgrades

### ISSUE THREAD

**Issue by Timeslice42** [Domaman202/LogisticsBridge#23]
LP: 0.10.4.5
LB: 1.4.5.1

As mentioned in #20 

If a crafting module recipe has an Advanced Satellite module upgrade on it, and there are items in the recipe with no satellite set, the items are sent to the default route, instead of the Crafting Manager's default satellite.

Will test [this artifact](https://github.com/KorewaLidesu/LogisticsBridge/suites/3494884207/artifacts/83233988) to see if it fixes the issue.

**Comment by Timeslice42** [comment]
I can confirm that this issue is fixed when using this artifact. Thank you!

**Comment by Domaman202** [comment]
thx for report!)
